branch-defaults:
  master:
    environment: yfi-env
    group_suffix: null
global:
  application_name: yfi
  branch: null
  default_ec2_keyname: FinancialIntel
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
